### ISSUE TITLE
Entities don't move back after removing from merge or when removing the config_entry

### ISSUE THREAD

**Issue by tbrasser** [EuleMitKeule/device-tools#13]
So a lot of my devices have too similar names, causing me to merge the wrong ones.

Not seeing easily how to revert this, other than fully redoing the affected integrations.

As when I remove or edit the merge, the original devices are not restored.

**Comment by tbrasser** [comment]
It seems a restart worked wonders.

Thanks so much for this integration!

**Comment by EuleMitKeule** [comment]
You're welcome, I'm glad it is of use for you.
The reversion process isn't completely stable I must admit. I hope it can be improved in the future.
