### ISSUE TITLE
Hot to add entities to a device

### ISSUE THREAD

**Issue by Tsjippy** [EuleMitKeule/device-tools#19]
thank you for this.

I created a new device, now I want to add new entites to it? How do I do that?
If I add one for instance sensor.voltage and click submit it sais succes but the battery still has no entity

**Comment by EuleMitKeule** [comment]
It should be working like that. Are there any related error messages in the logs perhaps?

**Comment by EuleMitKeule** [comment]
If there still is a problem feel free to comment here. Closing this for now.
