### ISSUE TITLE
Custom repository cannot be added, integration cannot be installed

### ISSUE THREAD

**Issue by andynash** [EuleMitKeule/device-tools#21]
I've tried using the My button in the ReadMe as well as manually within HACS, but either way it turns out saying the repository cannot be found.

Any suggestions?

**Comment by EuleMitKeule** [comment]
Hey, for me the link is working. Can somebody else confirm this? What exactly is the URL you are trying to add manually and what other options are you selecting?

**Comment by andynash** [comment]
Thanks guys, I've now had a chance to try using a desktop (I work on HA mainly using Android phones and tablets), and it worked fine - go figure. Perhaps a HACS or HA issue? I'll report it to them if it happens again with another integration.

I've just started trying things out, looks perfect for what I'm trying to achieve, thanks!
