### ISSUE TITLE
Create a brand logo for the integration.

### ISSUE THREAD

**Issue by Captnlink** [EuleMitKeule/device-tools#5]
Hi there!

I saw that the images for devices are broken.

![Screenshot_20240227-080142](https://github.com/EuleMitKeule/device-tools/assets/9320254/9dd069df-87dd-4709-b930-7a082467418b)

I used:
Devices Tools 1.8.1
HA core 2024.2.4

**Comment by EuleMitKeule** [comment]
Glad it is useful to someone else. Unfortunately it's a bit barebones and not 100% stable. I'm sure I'll have some time to improve it in the future and hope that someone might help working on it.

**Comment by ojoojoo** [comment]
> Glad it is useful to someone else. Unfortunately it's a bit barebones and not 100% stable. I'm sure I'll have some time to improve it in the future and hope that someone might help working on it.

It would be great to add a logo, if you have some time.... :) Thanks for the great integration!

**Comment by ojoojoo** [comment]
What I really meant was that it would be great if you can add a logo to a device by uploading a picture or something, not a logo for the program😬 I’m a technician and therefore absolutely not creative😂😂

**Comment by legantois** [comment]
+1 Is there a way to allow the user to choose the logo of the integration he/she wish to show ?
![image](https://github.com/EuleMitKeule/device-tools/assets/9216747/b5e840bf-3ca5-4bf6-8825-1abd94e9cd3b)

i

**Comment by EuleMitKeule** [comment]
> What I really meant was that it would be great if you can add a logo to a device by uploading a picture or something, not a logo for the program

Oh okay, that is something completely different not really related to this issue though.

@ojoojoo @legantois Would you please create a new issue regarding this feature request?

**Comment by vogtmh** [comment]
The broken icon definitely looks bad. I would suggest to just take an icon from this site - at least as a placeholder:
https://flaticons.net/search.php?search=device

The icons are royalty free and can be customized in shape and color as you'd like to. The site is my go-to source for many web projects :)

**Comment by EuleMitKeule** [comment]
I created an icon (via Dall-E) and submitted a PR to the brands repository.
https://github.com/home-assistant/brands/pull/5436
